### ISSUE TITLE
Could not resolve "ol/source/Stamen"

### ISSUE THREAD

**Issue by kankantian** [MelihAltintas/vue3-openlayers#245]
`vue3-openlayers` version  1.2.1 

```
Could not resolve "ol/source/Stamen"

    node_modules/.pnpm/registry.npmmirror.com+vue3-openlayers@1.2.0_nvpfb7uzosno3su6d7vhhy5xwe/node_modules/vue3-openlayers/dist/vue3-openlayers.es.js:45:19:
      45 │ import Stamen from "ol/source/Stamen";
         ╵                    ~~~~~~~~~~~~~~~~~~

  You can mark the path "ol/source/Stamen" as external to exclude it from the bundle, which will
  remove this error.

D:\workspace\sz\gk-app\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1649
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/.pnpm/registry.npmmirror.com+vue3-openlayers@1.2.0_nvpfb7uzosno3su6d7vhhy5xwe/node_modules/vue3-openlayers/dist/vue3-openlayers.es.js:45:19: ERROR: Could not resolve "ol/source/Stamen"
    at failureErrorWithLog (D:\workspace\sz\gk-app\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1649:15)
    at D:\workspace\sz\gk-app\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1058:25
    at D:\workspace\sz\gk-app\node_modules\.pnpm\registry.npmmirror.com+esbuild@0.18.20\node_modules\esbuild\lib\main.js:1525:9
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 19,
        file: 'node_modules/.pnpm/registry.npmmirror.com+vue3-openlayers@1.2.0_nvpfb7uzosno3su6d7vhhy5xwe/node_modules/vue3-openlayers/dist/vue3-openlayers.es.js',
        length: 18,
        line: 45,
        lineText: 'import Stamen from "ol/source/Stamen";',
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "ol/source/Stamen" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "ol/source/Stamen"'
    }
  ],
  warnings: []
}
```

**Comment by d-koppenhagen** [comment]
This happens, when using an incompatible OpenLayers version (OpenLayers 8 I assume). I released a pre-release with support for OpenLayers 8 which includes several breaking changes. Check out the release notes here:
https://github.com/MelihAltintas/vue3-openlayers/releases/tag/v2.0.0-0
