### ISSUE TITLE
AddFeatures does not work

### ISSUE THREAD

**Issue by kankantian** [MelihAltintas/vue3-openlayers#260]
I use `addFeatures` to add features to a vectorSource :
 `xpSource.value.source.addFeatures(features)` 
but an error has occurred:
```
vue3-openlayers.es.js:40135 Uncaught TypeError: feature2.getId is not a function
    at VectorSource.addToIndex_ (vue3-openlayers.es.js:40135:25)
    at VectorSource.addFeaturesInternal (vue3-openlayers.es.js:40170:16)
    at VectorSource.addFeatures (vue3-openlayers.es.js:40155:10)
```

**Comment by d-koppenhagen** [comment]
Hey @kankantian! Just for my interest: How have you solved it?

**Comment by kankantian** [comment]
Hi, there is no attribute named 'id' , it is a joke!
